/**
 * AuthFlow synthetic data seed.
 *
 * Idempotent: clears existing rows, then inserts with a fixed faker seed so the
 * data set is identical on every run. Every date is computed relative to the
 * moment the seed runs, so charts always show a live 90 day curve. Required
 * documents are generated by the real rules engine so the checklist on each
 * request stays consistent with the payer criteria.
 *
 * Synthetic data only. No real patient information.
 */

import { PrismaClient } from "@prisma/client"
import { faker } from "@faker-js/faker"
import { buildRequiredDocuments } from "../lib/rules"
import type {
  Diagnosis,
  LabResult,
  PatientChart,
  PriorTherapy,
  RuleCriteria,
} from "../types"

const prisma = new PrismaClient()

faker.seed(20260627)

const now = new Date()
const H = 3_600_000
const DAY = 24 * H
const minus = (ms: number) => new Date(now.getTime() - ms)
const plus = (ms: number) => new Date(now.getTime() + ms)
const addMs = (date: Date, ms: number) => new Date(date.getTime() + ms)
const ri = (min: number, max: number) => faker.number.int({ min, max })
const pick = <T>(arr: T[]): T => faker.helpers.arrayElement(arr)
const isoDate = (date: Date) => date.toISOString().slice(0, 10)
const titleCase = (s: string) =>
  s.replace(/\w\S*/g, (t) => t.charAt(0).toUpperCase() + t.slice(1).toLowerCase())

// ---------------------------------------------------------------------------
// Catalogs
// ---------------------------------------------------------------------------

const PAYERS = [
  { name: "Meridian Health Plan", planType: "Commercial PPO", formularyRef: "MHP-FRM-2026Q2" },
  { name: "BluePeak Insurance", planType: "Commercial HMO", formularyRef: "BPK-RX-2026" },
  { name: "Summit Medicare Advantage", planType: "Medicare Advantage", formularyRef: "SMA-PDL-2026" },
  { name: "Cascade Community Health", planType: "Medicaid Managed Care", formularyRef: "CCH-MCD-2026" },
  { name: "Evergreen National", planType: "Commercial PPO", formularyRef: "EVN-UM-2026" },
]

const SPECIALTIES = [
  "Rheumatology",
  "Gastroenterology",
  "Dermatology",
  "Endocrinology",
  "Neurology",
  "Oncology",
  "Internal Medicine",
  "Allergy and Immunology",
]

const COORDINATORS = [
  "Alex Rivera",
  "Jordan Kim",
  "Sam Patel",
  "Riley Chen",
  "Morgan Diaz",
]

// Map each medication to the specialty that typically prescribes it so the
// prescriber on each request, and the generated letters, read realistically.
const MED_SPECIALTY: Record<string, string> = {
  Adalimumab: "Rheumatology",
  Etanercept: "Rheumatology",
  Ustekinumab: "Gastroenterology",
  Secukinumab: "Rheumatology",
  Risankizumab: "Dermatology",
  Dupilumab: "Allergy and Immunology",
  Semaglutide: "Endocrinology",
  Tirzepatide: "Endocrinology",
  Empagliflozin: "Endocrinology",
  Ocrelizumab: "Neurology",
  Vedolizumab: "Gastroenterology",
  Pembrolizumab: "Oncology",
  Lisinopril: "Internal Medicine",
  Atorvastatin: "Internal Medicine",
}

type MedSeed = {
  name: string
  brandName: string
  drugClass: string
  ndc: string
  hcpcs?: string
  cpt?: string
  isSpecialty: boolean
  route: string
  indication: string
  criteria: RuleCriteria
}

function criteria(
  partial: Partial<RuleCriteria> & { criteriaSummary: string },
): RuleCriteria {
  return {
    paRequired: true,
    stepTherapyRequired: false,
    requiredDiagnoses: [],
    requiredPriorTherapies: [],
    requiredLabs: [],
    quantityLimit: false,
    ...partial,
  }
}

const SPECIALTY_MEDS: MedSeed[] = [
  {
    name: "Adalimumab", brandName: "Humira", drugClass: "TNF inhibitor",
    ndc: "00074-3799-02", hcpcs: "J0135", isSpecialty: true, route: "Subcutaneous",
    indication: "Moderate to severe inflammatory disease",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["L40", "M06", "K50"],
      requiredPriorTherapies: ["methotrexate", "conventional DMARD"],
      requiredLabs: ["TB screening", "Hepatitis B panel"],
      criteriaSummary:
        "Documented trial of methotrexate or a conventional DMARD, negative TB and Hepatitis B screening, and an approved inflammatory diagnosis.",
    }),
  },
  {
    name: "Etanercept", brandName: "Enbrel", drugClass: "TNF inhibitor",
    ndc: "58406-0445-04", hcpcs: "J1438", isSpecialty: true, route: "Subcutaneous",
    indication: "Rheumatoid arthritis and plaque psoriasis",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["M06", "L40"],
      requiredPriorTherapies: ["methotrexate"],
      requiredLabs: ["TB screening"],
      criteriaSummary:
        "Trial of methotrexate, negative TB screening, and a qualifying rheumatologic or dermatologic diagnosis.",
    }),
  },
  {
    name: "Ustekinumab", brandName: "Stelara", drugClass: "IL-12/23 inhibitor",
    ndc: "57894-0060-03", hcpcs: "J3357", isSpecialty: true, route: "Subcutaneous",
    indication: "Plaque psoriasis and Crohn's disease",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["L40", "K50"],
      requiredPriorTherapies: ["TNF inhibitor", "phototherapy"],
      requiredLabs: ["TB screening"],
      criteriaSummary:
        "Trial of a TNF inhibitor or phototherapy, negative TB screening, and a qualifying diagnosis.",
    }),
  },
  {
    name: "Secukinumab", brandName: "Cosentyx", drugClass: "IL-17 inhibitor",
    ndc: "00078-0639-97", hcpcs: "J3247", isSpecialty: true, route: "Subcutaneous",
    indication: "Psoriatic arthritis and ankylosing spondylitis",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["L40.50", "M45"],
      requiredPriorTherapies: ["conventional DMARD"],
      requiredLabs: ["TB screening"],
      criteriaSummary:
        "Trial of a conventional DMARD, negative TB screening, and psoriatic arthritis or ankylosing spondylitis.",
    }),
  },
  {
    name: "Risankizumab", brandName: "Skyrizi", drugClass: "IL-23 inhibitor",
    ndc: "00074-2042-02", hcpcs: "J2327", isSpecialty: true, route: "Subcutaneous",
    indication: "Moderate to severe plaque psoriasis",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["L40"],
      requiredPriorTherapies: ["topical corticosteroids", "phototherapy"],
      requiredLabs: ["TB screening"],
      criteriaSummary:
        "Trial of topical therapy or phototherapy, negative TB screening, and plaque psoriasis.",
    }),
  },
  {
    name: "Dupilumab", brandName: "Dupixent", drugClass: "IL-4 receptor antagonist",
    ndc: "00024-5914-01", hcpcs: "J3490", isSpecialty: true, route: "Subcutaneous",
    indication: "Atopic dermatitis and moderate to severe asthma",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["L20", "J45.40"],
      requiredPriorTherapies: ["topical corticosteroids"],
      requiredLabs: ["Eosinophil count"],
      criteriaSummary:
        "Trial of topical corticosteroids, supporting eosinophil count, and atopic dermatitis or moderate to severe asthma.",
    }),
  },
  {
    name: "Semaglutide", brandName: "Ozempic", drugClass: "GLP-1 receptor agonist",
    ndc: "00169-4132-12", isSpecialty: true, route: "Subcutaneous",
    indication: "Type 2 diabetes mellitus",
    criteria: criteria({
      stepTherapyRequired: true,
      quantityLimit: true,
      requiredDiagnoses: ["E11"],
      requiredPriorTherapies: ["metformin"],
      requiredLabs: ["HbA1c"],
      criteriaSummary:
        "Type 2 diabetes diagnosis, trial of metformin, and a recent HbA1c above goal. Quantity limit applies.",
    }),
  },
  {
    name: "Tirzepatide", brandName: "Mounjaro", drugClass: "GIP/GLP-1 receptor agonist",
    ndc: "00002-1506-80", isSpecialty: true, route: "Subcutaneous",
    indication: "Type 2 diabetes mellitus",
    criteria: criteria({
      stepTherapyRequired: true,
      quantityLimit: true,
      requiredDiagnoses: ["E11"],
      requiredPriorTherapies: ["metformin"],
      requiredLabs: ["HbA1c"],
      criteriaSummary:
        "Type 2 diabetes diagnosis, trial of metformin, and a recent HbA1c above goal. Quantity limit applies.",
    }),
  },
  {
    name: "Empagliflozin", brandName: "Jardiance", drugClass: "SGLT2 inhibitor",
    ndc: "00597-0152-30", isSpecialty: false, route: "Oral",
    indication: "Type 2 diabetes mellitus",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["E11"],
      requiredPriorTherapies: ["metformin"],
      requiredLabs: ["HbA1c", "eGFR"],
      criteriaSummary:
        "Type 2 diabetes diagnosis, trial of metformin, recent HbA1c, and an eGFR within the labeled range.",
    }),
  },
  {
    name: "Ocrelizumab", brandName: "Ocrevus", drugClass: "Anti-CD20 monoclonal antibody",
    ndc: "50242-0150-01", hcpcs: "J2350", cpt: "96413", isSpecialty: true, route: "Intravenous",
    indication: "Relapsing and primary progressive multiple sclerosis",
    criteria: criteria({
      requiredDiagnoses: ["G35"],
      requiredLabs: ["Hepatitis B panel", "CBC with differential"],
      criteriaSummary:
        "Confirmed multiple sclerosis, negative Hepatitis B screening, and a baseline CBC.",
    }),
  },
  {
    name: "Vedolizumab", brandName: "Entyvio", drugClass: "Integrin receptor antagonist",
    ndc: "64764-0300-20", hcpcs: "J3380", cpt: "96413", isSpecialty: true, route: "Intravenous",
    indication: "Ulcerative colitis and Crohn's disease",
    criteria: criteria({
      stepTherapyRequired: true,
      requiredDiagnoses: ["K51", "K50"],
      requiredPriorTherapies: ["TNF inhibitor"],
      requiredLabs: ["TB screening"],
      criteriaSummary:
        "Trial of a TNF inhibitor, negative TB screening, and ulcerative colitis or Crohn's disease.",
    }),
  },
  {
    name: "Pembrolizumab", brandName: "Keytruda", drugClass: "PD-1 inhibitor",
    ndc: "00006-3026-02", hcpcs: "J9271", cpt: "96413", isSpecialty: true, route: "Intravenous",
    indication: "Selected advanced solid tumors",
    criteria: criteria({
      requiredDiagnoses: ["C34", "C50", "C25"],
      requiredLabs: ["PD-L1 testing"],
      criteriaSummary:
        "Approved oncologic indication with PD-L1 testing where required by the label.",
    }),
  },
]

const GENERIC_MEDS: MedSeed[] = [
  {
    name: "Lisinopril", brandName: "Prinivil", drugClass: "ACE inhibitor",
    ndc: "00071-0207-23", isSpecialty: false, route: "Oral",
    indication: "Hypertension",
    criteria: criteria({
      paRequired: false,
      criteriaSummary: "No prior authorization required. Preferred formulary agent.",
    }),
  },
  {
    name: "Atorvastatin", brandName: "Lipitor", drugClass: "Statin",
    ndc: "00071-0155-23", isSpecialty: false, route: "Oral",
    indication: "Hyperlipidemia",
    criteria: criteria({
      paRequired: false,
      criteriaSummary: "No prior authorization required. Preferred formulary agent.",
    }),
  },
]

// ---------------------------------------------------------------------------
// Chart synthesis
// ---------------------------------------------------------------------------

const DX_SPECIFIC: Record<string, Diagnosis> = {
  L40: { code: "L40.0", label: "Psoriasis vulgaris" },
  "L40.50": { code: "L40.50", label: "Psoriatic arthritis" },
  M06: { code: "M06.9", label: "Rheumatoid arthritis" },
  M45: { code: "M45.9", label: "Ankylosing spondylitis" },
  K50: { code: "K50.90", label: "Crohn's disease" },
  K51: { code: "K51.90", label: "Ulcerative colitis" },
  E11: { code: "E11.9", label: "Type 2 diabetes mellitus" },
  L20: { code: "L20.9", label: "Atopic dermatitis" },
  "J45.40": { code: "J45.40", label: "Moderate persistent asthma" },
  G35: { code: "G35", label: "Multiple sclerosis" },
  C34: { code: "C34.90", label: "Malignant neoplasm of lung" },
  C50: { code: "C50.911", label: "Malignant neoplasm of breast" },
  C25: { code: "C25.9", label: "Malignant neoplasm of pancreas" },
}

const COMORBIDITIES: Diagnosis[] = [
  { code: "I10", label: "Essential hypertension" },
  { code: "E78.5", label: "Hyperlipidemia" },
  { code: "E66.9", label: "Obesity" },
  { code: "F41.1", label: "Generalized anxiety disorder" },
  { code: "M54.50", label: "Low back pain" },
]

const UNRELATED_DX: Diagnosis[] = [
  { code: "I10", label: "Essential hypertension" },
  { code: "E78.5", label: "Hyperlipidemia" },
  { code: "R51.9", label: "Headache, unspecified" },
]

function qualifyingDx(code: string): Diagnosis {
  return DX_SPECIFIC[code] ?? { code, label: "Documented condition" }
}

function failedTrial(req: string): PriorTherapy {
  const r = req.toLowerCase()
  if (r.includes("metformin"))
    return { name: "Metformin", drugClass: "Biguanide", outcome: "failed", note: "A1c remained above goal after 6 months" }
  if (r.includes("methotrexate") || r.includes("dmard"))
    return { name: "Methotrexate", drugClass: "Conventional DMARD", outcome: "failed", note: "Inadequate response after a 3 month trial" }
  if (r.includes("topical"))
    return { name: "Topical corticosteroids", drugClass: "Topical steroid", outcome: "failed", note: "Disease persisted despite adherence" }
  if (r.includes("tnf"))
    return { name: "Adalimumab", drugClass: "TNF inhibitor", outcome: "intolerant", note: "Discontinued for injection-site reactions" }
  if (r.includes("phototherapy") || r.includes("uvb"))
    return { name: "Narrowband UVB phototherapy", drugClass: "Phototherapy", outcome: "failed", note: "No durable response after 24 sessions" }
  return { name: titleCase(req), drugClass: "Prior therapy", outcome: "failed", note: "Documented trial and failure" }
}

function labResult(label: string): LabResult {
  const l = label.toLowerCase()
  const date = isoDate(minus(DAY * ri(6, 110)))
  if (l.includes("tb"))
    return { name: "QuantiFERON-TB Gold", value: "Negative", date, flag: "normal" }
  if (l.includes("hepatitis"))
    return { name: "Hepatitis B surface antigen", value: "Non-reactive", date, flag: "normal" }
  if (l.includes("hba1c") || l.includes("a1c"))
    return { name: "HbA1c", value: (ri(76, 108) / 10).toFixed(1), unit: "%", date, flag: "high" }
  if (l.includes("egfr"))
    return { name: "eGFR", value: String(ri(55, 96)), unit: "mL/min/1.73m2", date, flag: "normal" }
  if (l.includes("cbc"))
    return { name: "CBC with differential", value: "Within normal limits", date, flag: "normal" }
  if (l.includes("pd-l1"))
    return { name: "PD-L1 IHC 22C3", value: `TPS ${ri(20, 90)}%`, date, flag: "normal" }
  if (l.includes("eosin"))
    return { name: "Eosinophil count", value: String(ri(320, 720)), unit: "cells/uL", date, flag: "high" }
  return { name: label, value: "Documented", date, flag: "normal" }
}

type ChartProfile = "complete" | "missingStep" | "missingDx" | "missingLabs" | "minimal"

function makeChart(crit: RuleCriteria, profile: ChartProfile): PatientChart {
  const diagnoses: Diagnosis[] = []
  const priorTherapies: PriorTherapy[] = []
  const labs: LabResult[] = []

  // Qualifying diagnosis
  if (crit.requiredDiagnoses.length > 0) {
    diagnoses.push(
      profile === "missingDx"
        ? pick(UNRELATED_DX)
        : qualifyingDx(crit.requiredDiagnoses[0]),
    )
  }
  if (profile !== "minimal" && faker.datatype.boolean(0.6)) {
    diagnoses.push(pick(COMORBIDITIES))
  }

  // Step therapy
  if (crit.stepTherapyRequired || crit.requiredPriorTherapies.length > 0) {
    if (profile === "complete" || profile === "missingLabs" || profile === "missingDx") {
      priorTherapies.push(failedTrial(crit.requiredPriorTherapies[0] ?? "preferred agent"))
    } else if (profile === "missingStep") {
      priorTherapies.push({ name: "Ibuprofen", drugClass: "NSAID", outcome: "ongoing", note: "Current symptomatic therapy" })
    }
  }

  // Labs
  if (profile !== "missingLabs" && profile !== "minimal") {
    for (const lab of crit.requiredLabs) labs.push(labResult(lab))
  }
  if (profile === "complete" || profile === "missingStep") {
    labs.push(labResult("CBC with differential"))
  }

  return { diagnoses, priorTherapies, labs }
}

// ---------------------------------------------------------------------------
// Clinical prose
// ---------------------------------------------------------------------------

function justificationText(
  patientFirst: string,
  dx: string,
  drug: string,
  trial: PriorTherapy | undefined,
  plan: string,
): string {
  const trialPhrase = trial
    ? `an inadequate response to ${trial.name}`
    : `disease not controlled on first-line therapy`
  return `${patientFirst} has ${dx} with ${trialPhrase}. ${drug} is medically necessary to achieve disease control and is requested per ${plan} criteria.`
}

function letterText(args: {
  patientName: string
  dx: string
  drug: string
  trial?: PriorTherapy
  plan: string
  provider: string
  specialty: string
}): string {
  const { patientName, dx, drug, trial, plan, provider, specialty } = args
  const trialLine = trial
    ? `The patient previously completed a trial of ${trial.name}, which was ${trial.outcome}. `
    : `First-line management has not produced adequate disease control. `
  return [
    `To the Utilization Management Department at ${plan}:`,
    "",
    `I am writing to document the medical necessity of ${drug} for my patient, ${patientName}, who carries a diagnosis of ${dx}. ${trialLine}Continued disease activity warrants escalation of therapy.`,
    "",
    `In my clinical judgment as a ${specialty} specialist, ${drug} is the most appropriate next step and is consistent with accepted guidelines and the plan's published criteria. I respectfully request approval of this prior authorization.`,
    "",
    `Sincerely,`,
    `${provider}, ${specialty}`,
    "",
    `This letter is a draft prepared for clinician review. It is generated from synthetic data and must be reviewed and signed before submission.`,
  ].join("\n")
}

const DENIAL_REASONS = [
  "Submitted documentation did not establish disease severity meeting plan criteria.",
  "Step therapy trial duration was below the plan minimum of 90 days.",
  "Requested agent is non-formulary; a preferred alternative is available.",
  "Quantity requested exceeds the plan limit without supporting rationale.",
  "Diagnosis documentation was insufficient to confirm the approved indication.",
]

const APPEAL_STATES = ["Submitted", "Under review", "Peer-to-peer scheduled"]

// ---------------------------------------------------------------------------
// Status timeline
// ---------------------------------------------------------------------------

type EventSeed = { fromStatus: string | null; toStatus: string; note: string; createdAt: Date }

function buildTimeline(
  status: string,
  plan: string,
  times: {
    createdAt: Date
    submittedAt?: Date | null
    decisionAt?: Date | null
  },
  extra: { denialReason?: string; appealStatus?: string },
): EventSeed[] {
  const { createdAt, submittedAt, decisionAt } = times
  const events: EventSeed[] = []
  const docAt = addMs(createdAt, H * 2)

  if (status === "Draft") {
    return [{ fromStatus: null, toStatus: "Draft", note: "Request created from a point-of-care order.", createdAt }]
  }

  events.push({
    fromStatus: null,
    toStatus: "NeedsDocumentation",
    note: "Order captured at point of care; required documentation identified.",
    createdAt,
  })

  if (status === "NeedsDocumentation") {
    events.push({
      fromStatus: "NeedsDocumentation",
      toStatus: "NeedsDocumentation",
      note: "Chart auto-fill completed. Some required items still need to be captured.",
      createdAt: docAt,
    })
    return events
  }

  const readyAt = submittedAt ? addMs(submittedAt, -H * 3) : addMs(createdAt, H * 4)
  events.push({
    fromStatus: "NeedsDocumentation",
    toStatus: "ReadyToSubmit",
    note: "All required documentation satisfied from the chart.",
    createdAt: readyAt,
  })

  if (status === "ReadyToSubmit") return events

  if (submittedAt) {
    events.push({
      fromStatus: "ReadyToSubmit",
      toStatus: "Submitted",
      note: `Submitted to ${plan}.`,
      createdAt: submittedAt,
    })
  }

  if (status === "Submitted") return events

  const reviewAt = submittedAt ? addMs(submittedAt, H * ri(2, 10)) : addMs(createdAt, H * 8)
  events.push({
    fromStatus: "Submitted",
    toStatus: "InReview",
    note: `${plan} acknowledged the request; under adjudication.`,
    createdAt: reviewAt,
  })

  if (status === "InReview") return events

  if (status === "Approved" && decisionAt) {
    events.push({
      fromStatus: "InReview",
      toStatus: "Approved",
      note: `Approved by ${plan}.`,
      createdAt: decisionAt,
    })
  }

  if ((status === "Denied" || status === "Appealed") && decisionAt) {
    events.push({
      fromStatus: "InReview",
      toStatus: "Denied",
      note: `Denied: ${extra.denialReason ?? "criteria not met"}`,
      createdAt: decisionAt,
    })
  }

  if (status === "Appealed" && decisionAt) {
    events.push({
      fromStatus: "Denied",
      toStatus: "Appealed",
      note: `Appeal ${extra.appealStatus ?? "submitted"}.`,
      createdAt: addMs(decisionAt, H * ri(6, 36)),
    })
  }

  return events
}

// ---------------------------------------------------------------------------
// Build plan of requests
// ---------------------------------------------------------------------------

type Flow = "approved" | "denied" | "appealed" | "inreview" | "submitted" | "ready" | "open" | "draft"

type OrderSpec = {
  status: string
  profile: ChartProfile
  flow: Flow
  risk?: "atRisk" | "overdue"
}

function buildOrderSpecs(): OrderSpec[] {
  const specs: OrderSpec[] = []
  const push = (n: number, s: OrderSpec) => {
    for (let i = 0; i < n; i++) specs.push({ ...s })
  }

  push(16, { status: "Approved", profile: "complete", flow: "approved" })
  push(9, { status: "InReview", profile: "complete", flow: "inreview" })
  push(6, { status: "Submitted", profile: "complete", flow: "submitted" })
  push(5, { status: "ReadyToSubmit", profile: "complete", flow: "ready" })
  push(6, { status: "Denied", profile: "complete", flow: "denied" })
  push(3, { status: "Appealed", profile: "complete", flow: "appealed" })
  push(3, { status: "Draft", profile: "minimal", flow: "draft" })

  const needsProfiles: ChartProfile[] = [
    "missingStep", "missingLabs", "missingDx", "missingStep",
    "missingLabs", "missingStep", "missingDx", "missingLabs", "missingStep",
  ]
  needsProfiles.forEach((profile) => specs.push({ status: "NeedsDocumentation", profile, flow: "open" }))

  // Inject deadline pressure for the risk widgets.
  const markFirst = (status: string, flow: Flow, risk: "atRisk" | "overdue", count: number) => {
    let marked = 0
    for (const s of specs) {
      if (marked >= count) break
      if (s.status === status && s.flow === flow && !s.risk) {
        s.risk = risk
        marked++
      }
    }
  }
  markFirst("NeedsDocumentation", "open", "overdue", 2)
  markFirst("NeedsDocumentation", "open", "atRisk", 2)
  markFirst("ReadyToSubmit", "ready", "atRisk", 1)
  markFirst("InReview", "inreview", "atRisk", 2)
  markFirst("Submitted", "submitted", "atRisk", 1)

  return faker.helpers.shuffle(specs)
}

function timesFor(flow: Flow, risk?: "atRisk" | "overdue") {
  let createdAt: Date
  let submittedAt: Date | null = null
  let decisionAt: Date | null = null
  let deadline: Date

  const normalDeadline = () => plus(DAY * ri(3, 9))
  const riskDeadline = () =>
    risk === "overdue" ? minus(H * ri(2, 22)) : risk === "atRisk" ? plus(H * ri(15, 45)) : normalDeadline()

  switch (flow) {
    case "approved":
    case "denied":
    case "appealed": {
      createdAt = minus(DAY * ri(12, 82))
      submittedAt = addMs(createdAt, H * ri(6, 48))
      const reviewAt = addMs(submittedAt, H * ri(3, 14))
      decisionAt = addMs(reviewAt, H * ri(8, 110))
      if (decisionAt.getTime() > now.getTime() - H * 2) decisionAt = minus(H * ri(3, 96))
      if (decisionAt.getTime() < submittedAt.getTime()) decisionAt = addMs(submittedAt, H * ri(10, 60))
      deadline = addMs(submittedAt, DAY * ri(3, 7))
      break
    }
    case "inreview": {
      createdAt = minus(DAY * ri(1, 14))
      submittedAt = addMs(createdAt, H * ri(4, 40))
      if (submittedAt.getTime() >= now.getTime()) {
        submittedAt = new Date((createdAt.getTime() + now.getTime()) / 2)
      }
      deadline = riskDeadline()
      break
    }
    case "submitted": {
      createdAt = minus(DAY * ri(0, 6) + H * ri(1, 20))
      submittedAt = addMs(createdAt, H * ri(2, 18))
      if (submittedAt.getTime() >= now.getTime()) {
        submittedAt = new Date((createdAt.getTime() + now.getTime()) / 2)
      }
      deadline = riskDeadline()
      break
    }
    case "ready": {
      createdAt = minus(DAY * ri(0, 6) + H * ri(1, 20))
      deadline = riskDeadline()
      break
    }
    case "open": {
      createdAt = minus(DAY * ri(0, 12) + H * ri(1, 20))
      deadline = riskDeadline()
      break
    }
    case "draft": {
      createdAt = minus(H * ri(1, 30))
      deadline = plus(DAY * ri(4, 10))
      break
    }
  }

  const turnaroundHours =
    submittedAt && decisionAt
      ? Math.round(((decisionAt.getTime() - submittedAt.getTime()) / H) * 10) / 10
      : null

  return { createdAt, submittedAt, decisionAt, deadline, turnaroundHours }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log("Clearing existing data...")
  await prisma.generationLog.deleteMany()
  await prisma.statusEvent.deleteMany()
  await prisma.requiredDocument.deleteMany()
  await prisma.priorAuthRequest.deleteMany()
  await prisma.payerRule.deleteMany()
  await prisma.patient.deleteMany()
  await prisma.medication.deleteMany()
  await prisma.provider.deleteMany()
  await prisma.payer.deleteMany()

  console.log("Seeding payers, providers, medications...")
  const payers = await Promise.all(
    PAYERS.map((p) => prisma.payer.create({ data: p })),
  )

  const providers = await Promise.all(
    SPECIALTIES.map((specialty) =>
      prisma.provider.create({
        data: {
          firstName: faker.person.firstName(),
          lastName: faker.person.lastName(),
          npi: faker.string.numeric(10),
          specialty,
        },
      }),
    ),
  )
  const providerBySpecialty = new Map(providers.map((p) => [p.specialty, p]))

  const allMeds = [...SPECIALTY_MEDS, ...GENERIC_MEDS]
  const medRecords = await Promise.all(
    allMeds.map((m) =>
      prisma.medication.create({
        data: {
          name: m.name,
          brandName: m.brandName,
          drugClass: m.drugClass,
          ndc: m.ndc,
          hcpcs: m.hcpcs ?? null,
          cpt: m.cpt ?? null,
          isSpecialty: m.isSpecialty,
          route: m.route,
          indication: m.indication,
        },
      }),
    ),
  )
  const medByName = new Map(medRecords.map((r) => [r.name, r]))
  const seedByName = new Map(allMeds.map((m) => [m.name, m]))

  console.log("Seeding payer rules...")
  for (const payer of payers) {
    for (const med of allMeds) {
      const rec = medByName.get(med.name)!
      await prisma.payerRule.create({
        data: {
          payerId: payer.id,
          medicationId: rec.id,
          paRequired: med.criteria.paRequired,
          stepTherapyRequired: med.criteria.stepTherapyRequired,
          requiredDiagnoses: JSON.stringify(med.criteria.requiredDiagnoses),
          requiredPriorTherapies: JSON.stringify(med.criteria.requiredPriorTherapies),
          requiredLabs: JSON.stringify(med.criteria.requiredLabs),
          quantityLimit: med.criteria.quantityLimit,
          criteriaSummary: med.criteria.criteriaSummary,
        },
      })
    }
  }

  console.log("Seeding prior authorization requests...")
  const specs = buildOrderSpecs()
  let refSeq = 2500

  for (const spec of specs) {
    const med = pick(SPECIALTY_MEDS)
    const medRec = medByName.get(med.name)!
    const payer = pick(payers)
    const provider =
      providerBySpecialty.get(MED_SPECIALTY[med.name] ?? "Internal Medicine") ??
      pick(providers)
    const crit = med.criteria
    const chart = makeChart(crit, spec.profile)

    const firstName = faker.person.firstName()
    const lastName = faker.person.lastName()
    const patientName = `${firstName} ${lastName}`
    const memberId = `${faker.string.alpha({ length: 3, casing: "upper" })}${faker.string.numeric(9)}`
    const providerName = `Dr. ${provider.firstName} ${provider.lastName}`

    const t = timesFor(spec.flow, spec.risk)
    const hasLetter =
      spec.flow === "approved" ||
      spec.flow === "denied" ||
      spec.flow === "appealed" ||
      spec.flow === "inreview" ||
      spec.flow === "submitted" ||
      spec.flow === "ready"

    const docs = buildRequiredDocuments({
      drugName: med.name,
      criteria: crit,
      chart,
      memberId,
      providerName,
      providerNpi: provider.npi,
      hasLetterOfMedicalNecessity: hasLetter,
    })

    const primaryDx = chart.diagnoses[0] ?? { code: "R69", label: "Illness, unspecified" }
    const trial = chart.priorTherapies.find((p) =>
      ["failed", "intolerant", "partial"].includes(p.outcome),
    )

    const denialReason =
      spec.flow === "denied" || spec.flow === "appealed" ? pick(DENIAL_REASONS) : null
    const appealStatus = spec.flow === "appealed" ? pick(APPEAL_STATES) : null

    const isWorked = spec.flow !== "draft"
    const clinicalJustification = isWorked
      ? justificationText(firstName, primaryDx.label, med.name, trial, payer.name)
      : null
    const letterOfMedicalNecessity = hasLetter
      ? letterText({
          patientName,
          dx: primaryDx.label,
          drug: med.name,
          trial,
          plan: payer.name,
          provider: providerName,
          specialty: provider.specialty,
        })
      : null

    const events = buildTimeline(spec.status, payer.name, t, {
      denialReason: denialReason ?? undefined,
      appealStatus: appealStatus ?? undefined,
    })

    // Urgent and STAT skew toward deadline-pressured requests.
    const priority = spec.risk
      ? faker.helpers.weightedArrayElement([
          { weight: 5, value: "Urgent" },
          { weight: 3, value: "STAT" },
          { weight: 2, value: "Routine" },
        ])
      : faker.helpers.weightedArrayElement([
          { weight: 6, value: "Routine" },
          { weight: 3, value: "Urgent" },
          { weight: 1, value: "STAT" },
        ])

    refSeq += 1

    await prisma.priorAuthRequest.create({
      data: {
        referenceId: `PA-${refSeq}`,
        status: spec.status,
        priority,
        diagnosisCode: primaryDx.code,
        diagnosisLabel: primaryDx.label,
        clinicalJustification,
        letterOfMedicalNecessity,
        denialReason,
        appealStatus,
        assignedCoordinator: isWorked ? pick(COORDINATORS) : null,
        createdAt: t.createdAt,
        submittedAt: t.submittedAt,
        decisionAt: t.decisionAt,
        deadline: t.deadline,
        turnaroundHours: t.turnaroundHours,
        patient: {
          create: {
            firstName,
            lastName,
            dateOfBirth: faker.date.birthdate({ mode: "age", min: 19, max: 86 }),
            sex: pick(["Female", "Male"]),
            mrn: `MRN-${faker.string.numeric(7)}`,
            memberId,
            diagnoses: JSON.stringify(chart.diagnoses),
            priorTherapies: JSON.stringify(chart.priorTherapies),
            labs: JSON.stringify(chart.labs),
            weightKg: ri(52, 122),
            payer: { connect: { id: payer.id } },
          },
        },
        provider: { connect: { id: provider.id } },
        medication: { connect: { id: medRec.id } },
        payer: { connect: { id: payer.id } },
        requiredDocuments: {
          create: docs.map((d) => ({
            label: d.label,
            source: d.source,
            satisfied: d.satisfied,
            evidence: d.evidence ?? null,
          })),
        },
        statusEvents: {
          create: events.map((e) => ({
            fromStatus: e.fromStatus,
            toStatus: e.toStatus,
            note: e.note,
            createdAt: e.createdAt,
          })),
        },
      },
    })
  }

  console.log("Seeding AI generation telemetry...")
  const genLogs = []
  for (let i = 0; i < 64; i++) {
    const status = faker.helpers.weightedArrayElement([
      { weight: 24, value: "ok" },
      { weight: 1, value: "rate_limited" },
      { weight: 1, value: "error" },
      { weight: 1, value: "capped" },
    ])
    const realModel = status === "ok" && faker.datatype.boolean(0.65)
    genLogs.push({
      model: realModel ? "claude-opus-4-8" : "template",
      usedFallback: !realModel,
      status,
      latencyMs: realModel ? ri(1200, 4200) : ri(4, 40),
      inputTokens: realModel ? ri(360, 520) : null,
      outputTokens: realModel ? ri(280, 520) : null,
      createdAt: minus(DAY * ri(0, 14) + H * ri(0, 23)),
    })
  }
  await prisma.generationLog.createMany({ data: genLogs })

  const counts = await prisma.priorAuthRequest.groupBy({
    by: ["status"],
    _count: true,
  })
  console.log("Seed complete. Requests by status:")
  for (const c of counts) console.log(`  ${c.status}: ${c._count}`)
  console.log(`  Total: ${specs.length}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
